In [4]:
import numpy as np
import pandas as pd

## Import Dataset

In [5]:
df=pd.read_csv("Countries.csv")

In [6]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

## Data Extraction

### Country with the highest Population

In [7]:
df['Total_Population']=df['rural_population']+df['urban_population']
df['Total_Population']

0      41128771
1       2775634
2      44903225
3         79824
4      35588987
         ...
189    98186856
190     5043612
191    33696614
192    20017675
193    16320537
Name: Total_Population, Length: 194, dtype: int64

In [8]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,Total_Population
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President,41128771
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister,2775634
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President,44903225
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government,79824
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President,35588987

In [9]:
df[df['Total_Population']==df['Total_Population'].max()]['country']

75    India
Name: country, dtype: str

In [15]:
df.nlargest(1,'Total_Population')

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,Total_Population
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister,1417173173

### Capital with the highest Population

In [16]:
df[df['Total_Population']==df['Total_Population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: str

### Country with the Least Population

In [17]:
df[df['Total_Population']==df['Total_Population'].min()][['country','Total_Population']]

    country  Total_Population
179  Tuvalu             11312

### Capital with the Least Population

In [18]:
df[df['Total_Population']==df['Total_Population'].min()][['country','capital_city','Total_Population']]

    country capital_city  Total_Population
179  Tuvalu     Funafuti             11312

### Top 5 Countires with Highest Democratic Score

In [19]:
df.nlargest(5,'democracy_score')[['country','democracy_score']]

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

### Total Number of Unique Regions

In [20]:
df['region'].nunique()

22

### Total Number of Countries in Eastern Europe Region

In [56]:
df[df['region']=='Eastern Europe']['country'].nunique()

10

In [59]:
df[df['region']=='Eastern Europe']

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,Total_Population
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.0,82810.0,...,40.0000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President,9208701
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.0,50470.0,...,24.1667,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister,6465097
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.5,35238.7,...,25.5000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister,10526073
73,Hungary,Hungary,Hungarian forint,Budapest,Eastern Europe,Europe,Hungarian,47.000000,20.0,49030.0,...,14.0704,2657928,7025577,2.57,6.63,Flawed democracy,38.1,Viktor Orbán,Prime Minister,9683505
111,Moldova,Republic of Moldova,Moldovan leu,Chișinău,Eastern Europe,Europe,Moldovan,47.000000,29.0,22646.0,...,40.5941,1473227,1119250,2.51,5.85,Hybrid regime,31.2,Ion Chicu,Prime Minister,2592477
136,Poland,Republic of Poland,Polish zloty,Warsaw,Eastern Europe,Europe,Polish,52.000000,20.0,144610.0,...,28.2609,14974307,22587292,2.71,6.67,Flawed democracy,36.3,Mateusz Morawiecki,Prime Minister,37561599
139,Romania,Romania,New Romanian leu,Bucharest,Eastern Europe,Europe,Romanian,46.000000,25.0,135910.0,...,19.0909,8627368,10329298,3.05,6.38,Flawed democracy,37.4,Klaus Iohannis,President,18956666
140,Russia,Russian Federation,Russian ruble,Moscow,Eastern Europe,Europe,Russian,60.000000,100.0,2154940.0,...,16.2222,35708054,107847682,1.55,2.94,Authoritarian,35.0,Vladimir Putin,President,143555736
151,Slovak Republic,Slovak Republic,Euro,Bratislava,Eastern Europe,Europe,Slovak,48.666667,19.5,18830.0,...,21.3333,2503549,2928203,3.32,7.10,Flawed democracy,36.0,NaN,NaN,5431752
181,Ukraine,Ukraine,Ukrainian hryvnia,Kiev,Eastern Europe,Europe,Ukrainian,49.000000,32.0,413110.0,...,20.3310,11430780,26569220,2.41,5.69,Hybrid regime,38.9,Volodymyr Zelensky,President,38000000

### Political Leader of a Country with 2nd Highest Population

In [30]:
top2=df.nlargest(2,'Total_Population')
top2.iloc[1]['political_leader']

'Xi Jinping'

### Country with No Political Leader

In [48]:
df[df['political_leader'].isna()]['country']

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: str

### Country with Highest Population in Afiaca

In [53]:
df[df['continent']=='Africa'].nlargest(1,'Total_Population')

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,Total_Population
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.0,8.0,694500.0,...,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President,218541212

### Countries With 'Republic' word in their Name

In [60]:
txt='Republic'
count=0
for i in df['country_long']:
    if txt in i:
        print(i)
        count+=1
print(count)

Republic of Albania
People's Democratic Republic of Algeria
People's Republic of Angola
Argentine Republic
Republic of Armenia
Republic of Austria
Republic of Azerbaijan
People's Republic of Bangladesh
Republic of Belarus
Republic of Benin
Republic of Botswana
Federative Republic of Brazil
Republic of Bulgaria
Republic of Burundi
Republic of Cabo Verde
Republic of Cameroon
Central African Republic
Republic of Chad
Republic of Chile
People's Republic of China
Republic of Colombia
Republic of Congo
Republic of Costa Rica
Republic of Côte d'Ivoire
Republic of Croatia
Republic of Cuba
Republic of Cyprus
Czech Republic
Democratic People's Republic of Korea
Democratic Republic of the Congo
Republic of Djibouti
Dominican Republic
Republic of Ecuador
Arab Republic of Egypt
Republic of El Salvador
Republic of Equatorial Guinea
Republic of Estonia
Federal Democratic Republic of Ethiopia
Republic of Fiji
Republic of Finland
French Republic
Gabonese Republic
Federal Republic of Germany
Republic of Ghana
Hellenic Republic
Republic of Guatemala
Republic of Guinea
Republic of Guinea-Bissau
Co-operative Republic of Guyana
Republic of Haiti
Republic of Honduras
Republic of Iceland
Republic of India
Republic of Indonesia
Islamic Republic of Iran
Republic of Iraq
Italian Republic
Republic of Kazakhstan
Republic of Kenya
Republic of Kiribati
Republic of Korea
Kyrgyz Republic
Lao People's Democratic Republic
Republic of Latvia
Lebanese Republic
Republic of Liberia
Republic of Lithuania
Republic of Madagascar
Republic of Malawi
Republic of Maldives
Republic of Mali
Republic of Malta
Republic of the Marshall Islands
Islamic Republic of Mauritania
Republic of Mauritius
Republic of Moldova
Republic of Mozambique
Republic of the Union of Myanmar
Republic of Namibia
Republic of Nauru
Republic of Nicaragua
Republic of Niger
Federal Republic of Nigeria
Republic of North Macedonia
Islamic Republic of Pakistan
Republic of Palau
Republic of Panama
Republic of Paraguay
Republic of Peru
Republic of the Philippines
Republic of Poland
Portuguese Republic
Republic of Rwanda
Republic of San Marino
Democratic Republic of São Tomé and Principe
Republic of Senegal
Republic of Serbia
Republic of Seychelles
Republic of Sierra Leone
Republic of Singapore
Slovak Republic
Republic of Slovenia
Somali Democratic Republic
Republic of South Africa
Republic of South Sudan
Democratic Socialist Republic of Sri Lanka
Republic of the Sudan
Republic of Suriname
Syrian Arab Republic
Republic of Tajikistan
United Republic of Tanzania
Republic of The Gambia
Democratic Republic of Timor-Leste
Republic of Togo
Republic of Trinidad and Tobago
Republic of Tunisia
Republic of Turkey
Republic of Uganda
Oriental Republic of Uruguay
Republic of Uzbekistan
Republic of Vanuatu
Socialist Republic of Vietnam
Republic of Yemen
Republic of Zambia
Republic of Zimbabwe
125